-- ============================================================================
-- SECTION: Mood Board
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: moodboards
-- Purpose: Stores mood boards created by users.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.moodboards (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- TABLE: moodboard_items
-- Purpose: Stores the individual items within a mood board.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.moodboard_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    moodboard_id BIGINT NOT NULL REFERENCES public.moodboards(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL, -- 'image', 'text', 'link'
    content TEXT NOT NULL,
    url TEXT, -- Only for 'link' type
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- SECTION: Challenges
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: challenges
-- Purpose: Stores community challenges.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.challenges (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_date TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE
);

-- ----------------------------------------------------------------------------
-- TABLE: challenge_participants
-- Purpose: Tracks users participating in challenges.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.challenge_participants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenge_id BIGINT NOT NULL REFERENCES public.challenges(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    progress INT DEFAULT 0,
    UNIQUE(challenge_id, user_id)
);


-- ============================================================================
-- SECTION 4: RLS POLICIES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- POLICIES: moodboards
-- ----------------------------------------------------------------------------
ALTER TABLE public.moodboards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own moodboards." ON public.moodboards;
CREATE POLICY "Users can view their own moodboards."
    ON public.moodboards FOR SELECT
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can create their own moodboards." ON public.moodboards;
CREATE POLICY "Users can create their own moodboards."
    ON public.moodboards FOR INSERT
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can update their own moodboards." ON public.moodboards;
CREATE POLICY "Users can update their own moodboards."
    ON public.moodboards FOR UPDATE
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can delete their own moodboards." ON public.moodboards;
CREATE POLICY "Users can delete their own moodboards."
    ON public.moodboards FOR DELETE
    USING (user_id = auth.uid());


-- ----------------------------------------------------------------------------
-- POLICIES: moodboard_items
-- ----------------------------------------------------------------------------
ALTER TABLE public.moodboard_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view items on moodboards they own." ON public.moodboard_items;
CREATE POLICY "Users can view items on moodboards they own."
    ON public.moodboard_items FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM public.moodboards
        WHERE moodboards.id = moodboard_items.moodboard_id AND moodboards.user_id = auth.uid()
    ));

DROP POLICY IF EXISTS "Users can add items to moodboards they own." ON public.moodboard_items;
CREATE POLICY "Users can add items to moodboards they own."
    ON public.moodboard_items FOR INSERT
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.moodboards
        WHERE moodboards.id = moodboard_items.moodboard_id AND moodboards.user_id = auth.uid()
    ));

DROP POLICY IF EXISTS "Users can delete items from moodboards they own." ON public.moodboard_items;
CREATE POLICY "Users can delete items from moodboards they own."
    ON public.moodboard_items FOR DELETE
    USING (EXISTS (
        SELECT 1 FROM public.moodboards
        WHERE moodboards.id = moodboard_items.moodboard_id AND moodboards.user_id = auth.uid()
    ));

-- ----------------------------------------------------------------------------
-- POLICIES: challenges
-- ----------------------------------------------------------------------------
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "All users can view challenges." ON public.challenges;
CREATE POLICY "All users can view challenges."
    ON public.challenges FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Verified users can create challenges." ON public.challenges;
CREATE POLICY "Verified users can create challenges."
    ON public.challenges FOR INSERT
    WITH CHECK ((SELECT verified FROM public.profiles WHERE id = auth.uid()) = true);

DROP POLICY IF EXISTS "Verified users can update challenges." ON public.challenges;
CREATE POLICY "Verified users can update challenges."
    ON public.challenges FOR UPDATE
    USING ((SELECT verified FROM public.profiles WHERE id = auth.uid()) = true);

-- ----------------------------------------------------------------------------
-- POLICIES: challenge_participants
-- ----------------------------------------------------------------------------
ALTER TABLE public.challenge_participants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "All users can view participants." ON public.challenge_participants;
CREATE POLICY "All users can view participants."
    ON public.challenge_participants FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Users can join a challenge." ON public.challenge_participants;
CREATE POLICY "Users can join a challenge."
    ON public.challenge_participants FOR INSERT
    WITH CHECK ( user_id = auth.uid() );

DROP POLICY IF EXISTS "Users can leave a challenge." ON public.challenge_participants;
CREATE POLICY "Users can leave a challenge."
    ON public.challenge_participants FOR DELETE
    USING ( user_id = auth.uid() );
