-- ============================================================================
-- TABLE: followers
-- Purpose: Stores the relationship between users who follow each other.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(follower_id, following_id) -- A user can only follow another user once
);

COMMENT ON TABLE public.followers IS 'Stores the many-to-many relationship between users who are following each other.';
COMMENT ON COLUMN public.followers.follower_id IS 'The user who is initiating the follow.';
COMMENT ON COLUMN public.followers.following_id IS 'The user who is being followed.';


-- ============================================================================
-- RLS Policies for followers
-- ============================================================================
ALTER TABLE public.followers ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view all follower relationships.
-- This is often public information in social apps (e.g., who follows whom).
CREATE POLICY "Follower relationships are public."
    ON public.followers FOR SELECT
    USING (true);

-- Policy: Users can follow other users.
-- A user can insert a record where they are the 'follower_id'.
CREATE POLICY "Users can follow other users."
    ON public.followers FOR INSERT
    WITH CHECK (auth.uid() = follower_id);

-- Policy: Users can unfollow other users.
-- A user can delete a record where they are the 'follower_id'.
CREATE POLICY "Users can unfollow users they follow."
    ON public.followers FOR DELETE
    USING (auth.uid() = follower_id);
