-- ============================================================================
-- PINNED CHATS FEATURE
-- ============================================================================
-- Allows users to pin important chats to the top of their chat list
-- ============================================================================

-- ============================================================================
-- SECTION 1: CREATE PINNED CHATS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pinned_chats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    chat_id BIGINT REFERENCES public.chats(id) ON DELETE CASCADE NOT NULL,
    pinned_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(user_id, chat_id)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_pinned_chats_user_id ON public.pinned_chats(user_id);
CREATE INDEX IF NOT EXISTS idx_pinned_chats_chat_id ON public.pinned_chats(chat_id);

-- ============================================================================
-- SECTION 2: RLS POLICIES
-- ============================================================================

ALTER TABLE public.pinned_chats ENABLE ROW LEVEL SECURITY;

-- Users can only see their own pinned chats
CREATE POLICY "Users can view their own pinned chats"
    ON public.pinned_chats FOR SELECT
    USING (auth.uid() = user_id);

-- Users can pin their own chats
CREATE POLICY "Users can pin their own chats"
    ON public.pinned_chats FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Users can unpin their own chats
CREATE POLICY "Users can unpin their own chats"
    ON public.pinned_chats FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================================================
-- SECTION 3: TOGGLE PIN FUNCTION
-- ============================================================================

CREATE OR REPLACE FUNCTION public.toggle_pin_chat(p_chat_id BIGINT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID := auth.uid();
    v_is_pinned BOOLEAN;
BEGIN
    -- Check if chat is already pinned
    SELECT EXISTS(
        SELECT 1 FROM public.pinned_chats
        WHERE user_id = v_user_id AND chat_id = p_chat_id
    ) INTO v_is_pinned;

    IF v_is_pinned THEN
        -- Unpin
        DELETE FROM public.pinned_chats
        WHERE user_id = v_user_id AND chat_id = p_chat_id;
        
        RETURN jsonb_build_object(
            'success', true,
            'is_pinned', false,
            'message', 'Chat unpinned'
        );
    ELSE
        -- Pin
        INSERT INTO public.pinned_chats (user_id, chat_id)
        VALUES (v_user_id, p_chat_id);
        
        RETURN jsonb_build_object(
            'success', true,
            'is_pinned', true,
            'message', 'Chat pinned'
        );
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY INVOKER;

-- ============================================================================
-- SECTION 4: GET PINNED CHAT IDS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_pinned_chat_ids()
RETURNS TABLE (chat_id BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT pc.chat_id
    FROM public.pinned_chats pc
    WHERE pc.user_id = auth.uid()
    ORDER BY pc.pinned_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY INVOKER;

-- ============================================================================
-- SECTION 5: GRANT PERMISSIONS
-- ============================================================================

GRANT SELECT, INSERT, DELETE ON public.pinned_chats TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pinned_chats_id_seq TO authenticated;
GRANT EXECUTE ON FUNCTION public.toggle_pin_chat(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pinned_chat_ids() TO authenticated;

-- ============================================================================
-- END OF FILE
-- ============================================================================
