-- ============================================================================
-- TABLE: posts
-- Purpose: Stores user-generated posts for their profile feeds.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
    -- You can add more fields here later, like image_url, etc.
);

COMMENT ON TABLE public.posts IS 'Stores user-generated posts that appear on their profiles.';


-- ============================================================================
-- RLS Policies for posts
-- ============================================================================
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Policy: Posts are publicly viewable.
CREATE POLICY "Posts are viewable by everyone."
    ON public.posts FOR SELECT
    USING (true);

-- Policy: Users can create their own posts.
CREATE POLICY "Users can insert their own posts."
    ON public.posts FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own posts.
CREATE POLICY "Users can update their own posts."
    ON public.posts FOR UPDATE
    USING (auth.uid() = user_id);

-- Policy: Users can delete their own posts.
CREATE POLICY "Users can delete their own posts."
    ON public.posts FOR DELETE
    USING (auth.uid() = user_id);
