-- ============================================================================
--                    SCHEMA.SQL - FINAL CONSOLIDATED STATE
-- ============================================================================
-- Description: Contains all active table definitions, types, and RLS policies.
--              Tables that were deprecated (dm_requests, reports, blocked_users)
--              have been excluded.
-- ============================================================================

-- ============================================================================
-- SECTION 1: ENUM TYPES
-- ============================================================================

CREATE TYPE public.rsvp_status AS ENUM ('going', 'interested', 'not_going');

CREATE TYPE public.relationship_status AS ENUM (
    'pending',    -- A follow request is waiting for approval
    'approved',   -- The follow is active
    'blocked'     -- The 'user_one_id' has blocked 'user_two_id'
);

CREATE TYPE public.notification_type AS ENUM (
    'follow_request',
    'new_follower',
    'new_like',
    'new_comment',
    'new_repost'
);

-- ============================================================================
-- SECTION 2: CORE TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: profiles
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID NOT NULL PRIMARY KEY,
    name TEXT,
    username TEXT UNIQUE,
    avatar_url TEXT,
    gender TEXT,
    bio TEXT,
    verified BOOLEAN DEFAULT FALSE NOT NULL,
    is_private BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

COMMENT ON COLUMN public.profiles.verified IS 'Indicates if a user is verified and can access special features like event creation.';
COMMENT ON COLUMN public.profiles.is_private IS 'If true, users must request to follow this profile.';

-- ----------------------------------------------------------------------------
-- TABLE: relationships (Handles Follows and Blocks)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.relationships (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_one_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_two_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status public.relationship_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- 'user_one_id' is the initiator (follower/blocker)
    -- 'user_two_id' is the target (followed/blocked)
    CONSTRAINT unique_relationship UNIQUE (user_one_id, user_two_id),
    CONSTRAINT check_not_self_relationship CHECK (user_one_id <> user_two_id)
);

-- ============================================================================
-- SECTION 3: MESSAGING & CHATS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.chats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    type TEXT NOT NULL, -- 'dm' or 'group'
    name TEXT,
    avatar_url TEXT,
    description TEXT,
    created_by UUID REFERENCES public.profiles(id) DEFAULT auth.uid(),
    is_public BOOLEAN DEFAULT TRUE,
    history_visible BOOLEAN DEFAULT TRUE,
    invite_code UUID DEFAULT gen_random_uuid()
);

CREATE TABLE IF NOT EXISTS public.participants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chat_id BIGINT REFERENCES public.chats(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    UNIQUE(chat_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    chat_id BIGINT REFERENCES public.chats(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    content TEXT,
    is_edited BOOLEAN DEFAULT FALSE,
    attachment_url TEXT,
    attachment_metadata JSONB,
    reactions JSONB,
    read_by UUID[] DEFAULT ARRAY[]::UUID[],
    deleted_for UUID[],
    is_pinned BOOLEAN DEFAULT FALSE,
    reply_to_message_id BIGINT NULL,
    CONSTRAINT messages_reply_to_message_id_fkey FOREIGN KEY (reply_to_message_id) 
        REFERENCES public.messages(id) ON DELETE SET NULL
);

-- ============================================================================
-- SECTION 4: SOCIAL FEED (Posts, Comments, Likes)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT,
    media_urls JSONB, -- Array of objects: [{url: "...", type: "image"}]
    poll JSONB,       -- {question: "...", options: [...]}
    quote_of_id BIGINT REFERENCES public.posts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_post_has_content CHECK (
        content IS NOT NULL OR 
        media_urls IS NOT NULL OR 
        poll IS NOT NULL OR 
        quote_of_id IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    parent_comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.post_likes (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.post_reposts (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.comment_likes (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    comment_id BIGINT NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (user_id, comment_id)
);

-- ============================================================================
-- SECTION 5: EVENTS & STATUS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creator_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    thumbnail TEXT,
    date_time TIMESTAMPTZ NOT NULL,
    meet_link TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.event_rsvps (
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status public.rsvp_status NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.statuses (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL DEFAULT 'image',
    caption TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + '1 day'::interval)
);

CREATE TABLE IF NOT EXISTS public.status_views (
    status_id BIGINT NOT NULL REFERENCES public.statuses(id) ON DELETE CASCADE,
    viewer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (status_id, viewer_id)
);

-- ============================================================================
-- SECTION 6: LISTS & NOTIFICATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.lists (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    owner_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    is_private BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT lists_owner_id_name_key UNIQUE (owner_id, name)
);

CREATE TABLE IF NOT EXISTS public.list_members (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    list_id BIGINT NOT NULL REFERENCES public.lists(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT list_members_list_id_user_id_key UNIQUE (list_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    actor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type public.notification_type NOT NULL,
    entity_id BIGINT,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT check_not_self_notification CHECK (user_id <> actor_id)
);

-- ============================================================================
-- SECTION 7: RLS POLICIES
-- ============================================================================

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_rsvps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.list_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_reposts ENABLE ROW LEVEL SECURITY;

-- Profiles
CREATE POLICY "Public profiles are viewable by everyone." 
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." 
    ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile." 
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Relationships (Follows/Blocks)
CREATE POLICY "Users can manage their own relationships"
    ON public.relationships FOR ALL
    USING ( auth.uid() = user_one_id OR auth.uid() = user_two_id );

CREATE POLICY "Users can view all approved/blocked relationships"
    ON public.relationships FOR SELECT
    USING ( status IN ('approved', 'blocked') );

CREATE POLICY "Users can view their own pending requests"
    ON public.relationships FOR SELECT
    USING ( status = 'pending' AND (auth.uid() = user_one_id OR auth.uid() = user_two_id) );

-- Chats
CREATE POLICY "Authenticated users can create chats." 
    ON public.chats FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Users can view chats they participate in." 
    ON public.chats FOR SELECT 
    USING (EXISTS (SELECT 1 FROM public.participants WHERE chat_id = chats.id AND user_id = auth.uid()));

-- Participants
CREATE POLICY "Chat creators can add participants." 
    ON public.participants FOR INSERT 
    WITH CHECK ((SELECT created_by FROM public.chats WHERE id = chat_id) = auth.uid());

CREATE POLICY "Users can view participants of chats they are in." 
    ON public.participants FOR SELECT 
    USING (EXISTS (SELECT 1 FROM public.participants WHERE chat_id = participants.chat_id AND user_id = auth.uid()));

-- Messages
CREATE POLICY "Users can send messages in chats they participate in."
    ON public.messages FOR INSERT TO authenticated
    WITH CHECK ((user_id = auth.uid()) AND (chat_id IN (SELECT p.chat_id FROM public.participants p WHERE p.user_id = auth.uid())));

CREATE POLICY "Users can view messages in chats they participate in."
    ON public.messages FOR SELECT TO authenticated
    USING (chat_id IN (SELECT p.chat_id FROM public.participants p WHERE p.user_id = auth.uid()));

CREATE POLICY "Users can delete their own messages."
    ON public.messages FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users can update their own messages."
    ON public.messages FOR UPDATE TO authenticated USING (true) WITH CHECK (user_id = auth.uid());

-- Events (Updated for Democratized/Verified Model)
CREATE POLICY "Public can read all events." 
    ON public.events FOR SELECT USING (true);

CREATE POLICY "Authenticated users can create events" ON public.events
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Creator can manage their own event" ON public.events
    FOR ALL USING (auth.uid() = creator_id);

CREATE POLICY "Verified users can create events."
    ON public.events FOR INSERT
    WITH CHECK ((SELECT verified FROM public.profiles WHERE id = auth.uid()) = true);

CREATE POLICY "Verified users or event creators can update events."
    ON public.events FOR UPDATE
    USING ((SELECT verified FROM public.profiles WHERE id = auth.uid()) = true OR creator_id = auth.uid());

-- Event RSVPs
CREATE POLICY "Public can read all RSVPs." 
    ON public.event_rsvps FOR SELECT USING (true);

CREATE POLICY "Users can insert their own RSVP." 
    ON public.event_rsvps FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own RSVP." 
    ON public.event_rsvps FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own RSVP." 
    ON public.event_rsvps FOR DELETE USING (auth.uid() = user_id);

-- Statuses
CREATE POLICY "Users can view their own statuses" ON public.statuses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own statuses" ON public.statuses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own statuses" ON public.statuses FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Users can view all non-expired statuses" ON public.statuses FOR SELECT USING (expires_at > NOW());

-- Status Views
CREATE POLICY "Users can view their own views" ON public.status_views FOR SELECT USING (auth.uid() = viewer_id);
CREATE POLICY "Users can mark a status as viewed" ON public.status_views FOR INSERT WITH CHECK (auth.uid() = viewer_id);

-- Lists
CREATE POLICY "Users can view their own lists." ON public.lists FOR SELECT USING (owner_id = auth.uid());
CREATE POLICY "Users can create their own lists." ON public.lists FOR INSERT WITH CHECK (owner_id = auth.uid());
CREATE POLICY "Users can update their own lists." ON public.lists FOR UPDATE USING (owner_id = auth.uid());
CREATE POLICY "Users can delete their own lists." ON public.lists FOR DELETE USING (owner_id = auth.uid());

-- List Members
CREATE POLICY "Users can view members of lists they own." ON public.list_members FOR SELECT USING (EXISTS (SELECT 1 FROM public.lists WHERE lists.id = list_members.list_id AND lists.owner_id = auth.uid()));
CREATE POLICY "Users can add members to lists they own." ON public.list_members FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.lists WHERE lists.id = list_members.list_id AND lists.owner_id = auth.uid()));
CREATE POLICY "Users can remove members from lists they own." ON public.list_members FOR DELETE USING (EXISTS (SELECT 1 FROM public.lists WHERE lists.id = list_members.list_id AND lists.owner_id = auth.uid()));

-- Notifications
CREATE POLICY "Users can only see their own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own notifications (mark as read)" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-- Posts & Feed
CREATE POLICY "Posts are viewable by everyone" ON public.posts FOR SELECT USING (true);
CREATE POLICY "Users can create their own posts" ON public.posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own posts" ON public.posts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own posts" ON public.posts FOR DELETE USING (auth.uid() = user_id);

-- Comments
CREATE POLICY "Comments are viewable by everyone" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Users can create comments" ON public.comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own comments" ON public.comments FOR DELETE USING (auth.uid() = user_id);

-- Likes
CREATE POLICY "Likes are viewable by everyone" ON public.post_likes FOR SELECT USING (true);
CREATE POLICY "Users can like/unlike posts" ON public.post_likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Comment likes are viewable by everyone" ON public.comment_likes FOR SELECT USING (true);
CREATE POLICY "Users can like/unlike comments" ON public.comment_likes FOR ALL USING (auth.uid() = user_id);

-- Reposts
CREATE POLICY "Reposts are viewable by everyone" ON public.post_reposts FOR SELECT USING (true);
CREATE POLICY "Users can repost/unrepost posts" ON public.post_reposts FOR ALL USING (auth.uid() = user_id);

-- Storage (bucket: 'post_media')
CREATE POLICY "Allow public read access to post media"
    ON storage.objects FOR SELECT USING ( bucket_id = 'post_media' );

CREATE POLICY "Allow authenticated users to upload post media"
    ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'post_media' AND auth.role() = 'authenticated' );

CREATE POLICY "Allow users to delete their own post media"
    ON storage.objects FOR DELETE USING ( bucket_id = 'post_media' AND auth.uid() = owner );

CREATE POLICY "Allow users to update their own post media"
    ON storage.objects FOR UPDATE USING ( bucket_id = 'post_media' AND auth.uid() = owner );

-- ============================================================================
-- SECTION 8: REALTIME
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
  
  -- Add relevant tables
  ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
  ALTER PUBLICATION supabase_realtime ADD TABLE public.chats;
  ALTER PUBLICATION supabase_realtime ADD TABLE public.participants;
  ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
END$$;