-- ============================================================
-- 19_create_challenges_table.sql
-- Creates the missing challenges and challenge_participants tables
-- with all columns and constraints.
-- ============================================================

-- 1. Create challenges table
CREATE TABLE IF NOT EXISTS public.challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  
  -- Core properties
  start_date TIMESTAMPTZ DEFAULT now(),
  end_date TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  
  -- Extended properties (from 10)
  cover_image TEXT,
  rules TEXT,
  prize_description TEXT,
  max_participants INTEGER,
  requires_proof BOOLEAN DEFAULT true,
  is_featured BOOLEAN DEFAULT false,
  winner_id UUID REFERENCES public.profiles(id),
  winner_declared_at TIMESTAMPTZ,
  category TEXT DEFAULT 'general',
  
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create challenge_participants table
CREATE TABLE IF NOT EXISTS public.challenge_participants (
  challenge_id BIGINT NOT NULL REFERENCES public.challenges(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  
  -- Extended properties (from 10/12)
  status TEXT DEFAULT 'joined' CHECK (status IN ('joined', 'submitted', 'verified', 'rejected', 'winner')),
  rank INTEGER,
  score INTEGER DEFAULT 0,
  completed_at TIMESTAMPTZ,
  
  PRIMARY KEY (challenge_id, user_id)
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_challenges_featured ON public.challenges(is_featured, is_active);
CREATE INDEX IF NOT EXISTS idx_challenges_category ON public.challenges(category);
CREATE INDEX IF NOT EXISTS idx_challenge_participants_status ON public.challenge_participants(status);
CREATE INDEX IF NOT EXISTS idx_challenges_creator ON public.challenges(created_by);

-- 4. RLS Policies

-- Enable RLS
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_participants ENABLE ROW LEVEL SECURITY;

-- Challenges Policies
DO $$ BEGIN
  -- Anyone can view challenges
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenges_select' AND tablename = 'challenges') THEN
    CREATE POLICY challenges_select ON public.challenges FOR SELECT USING (true);
  END IF;
  
  -- Verified/Authorized users can create (checked via function usually, but allow authenticated for now)
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenges_insert' AND tablename = 'challenges') THEN
    CREATE POLICY challenges_insert ON public.challenges FOR INSERT WITH CHECK (created_by = auth.uid());
  END IF;
  
  -- Creator can update
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenges_update' AND tablename = 'challenges') THEN
    CREATE POLICY challenges_update ON public.challenges FOR UPDATE USING (created_by = auth.uid());
  END IF;
  
  -- Creator can delete
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenges_delete' AND tablename = 'challenges') THEN
    CREATE POLICY challenges_delete ON public.challenges FOR DELETE USING (created_by = auth.uid());
  END IF;
END $$;

-- Participants Policies
DO $$ BEGIN
  -- Anyone can view participants (public leaderboard)
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenge_participants_select' AND tablename = 'challenge_participants') THEN
    CREATE POLICY challenge_participants_select ON public.challenge_participants FOR SELECT USING (true);
  END IF;
  
  -- Users can join (insert)
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenge_participants_insert' AND tablename = 'challenge_participants') THEN
    CREATE POLICY challenge_participants_insert ON public.challenge_participants FOR INSERT WITH CHECK (user_id = auth.uid());
  END IF;
  
  -- Users can leave (delete own)
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenge_participants_delete' AND tablename = 'challenge_participants') THEN
    CREATE POLICY challenge_participants_delete ON public.challenge_participants FOR DELETE USING (user_id = auth.uid());
  END IF;
  
  -- Users can update status? Usually handled via RPC/trigger, but maybe allow update for own record if needed.
  -- Restricting update to RPC or specific conditions is safer, but let's allow owner update for flexibility if used directly.
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'challenge_participants_update' AND tablename = 'challenge_participants') THEN
     CREATE POLICY challenge_participants_update ON public.challenge_participants FOR UPDATE USING (user_id = auth.uid());
  END IF;
END $$;

-- 5. Force schema cache reload
NOTIFY pgrst, 'reload schema';
